/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evm;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class Voting_page extends javax.swing.JFrame {
   String a_number = Login_page.userName;
   
   
    Voting_page(String x)
    {
        x=aadhaar_number;
        System.out.println(x);
        
    }/**
     * Creates new form Voting_page
     */
    Connection con;
    PreparedStatement ps;
    
    public static String aadhaar_number;
    public Voting_page() {
        
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/evm","root","11113112");
        }
        catch(Exception ex)
        {
         JOptionPane.showMessageDialog(this,ex);   
         }
    }

    
    
    
     public void choice(String party_name){
        try{
             String sql="insert into voting values(?,?)";
              ps=con.prepareStatement(sql);
              ps.setString(1,a_number);
              /*System.out.println(aadhaar_number);*/
              ps.setString(2,party_name);
              ps.executeUpdate();
              JOptionPane.showMessageDialog(null, "Congratulations, you have casted your VOTE");
              this.setVisible(false);
            }
        catch(Exception ex){
                System.out.println(ex);
            } 
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aap_label = new javax.swing.JLabel();
        congress_label = new javax.swing.JLabel();
        bjp_label = new javax.swing.JLabel();
        bsp_label = new javax.swing.JLabel();
        cp_label = new javax.swing.JLabel();
        Partyname_label = new javax.swing.JLabel();
        aap_button = new javax.swing.JButton();
        sp_label = new javax.swing.JLabel();
        ncp_label = new javax.swing.JLabel();
        nota_label = new javax.swing.JLabel();
        nota_button1 = new javax.swing.JButton();
        congress_button1 = new javax.swing.JButton();
        bjp_button1 = new javax.swing.JButton();
        bsp_button = new javax.swing.JButton();
        cp_button = new javax.swing.JButton();
        sp_button = new javax.swing.JButton();
        ncp_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aap_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/aap_1.png"))); // NOI18N
        aap_label.setText("jLabel1");

        congress_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/congress.png"))); // NOI18N
        congress_label.setText("jLabel2");

        bjp_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/bjp.png"))); // NOI18N
        bjp_label.setText("jLabel3");

        bsp_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/bsp1.png"))); // NOI18N
        bsp_label.setText("jLabel4");

        cp_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/CPI.png"))); // NOI18N
        cp_label.setText("jLabel5");

        Partyname_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Partyname_label.setText("PLEASE CLICK ON THE PARTY NAME TO VOTE");

        aap_button.setBackground(new java.awt.Color(102, 204, 255));
        aap_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aap_button.setText("AAP");
        aap_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aap_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aap_buttonActionPerformed(evt);
            }
        });

        sp_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/sp1.png"))); // NOI18N
        sp_label.setText("jLabel7");

        ncp_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/ncp1.png"))); // NOI18N
        ncp_label.setText("jLabel8");

        nota_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evm/nota1.png"))); // NOI18N
        nota_label.setText("jLabel9");

        nota_button1.setBackground(new java.awt.Color(102, 204, 255));
        nota_button1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nota_button1.setText("NOTA");
        nota_button1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nota_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota_button1ActionPerformed(evt);
            }
        });

        congress_button1.setBackground(new java.awt.Color(102, 204, 255));
        congress_button1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        congress_button1.setText("CONGRESS");
        congress_button1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        congress_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congress_button1ActionPerformed(evt);
            }
        });

        bjp_button1.setBackground(new java.awt.Color(102, 204, 255));
        bjp_button1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        bjp_button1.setText("BJP");
        bjp_button1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bjp_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjp_button1ActionPerformed(evt);
            }
        });

        bsp_button.setBackground(new java.awt.Color(102, 204, 255));
        bsp_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bsp_button.setText("BSP");
        bsp_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bsp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsp_buttonActionPerformed(evt);
            }
        });

        cp_button.setBackground(new java.awt.Color(102, 204, 255));
        cp_button.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        cp_button.setText("CP");
        cp_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_buttonActionPerformed(evt);
            }
        });

        sp_button.setBackground(new java.awt.Color(102, 204, 255));
        sp_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sp_button.setText("SP");
        sp_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp_buttonActionPerformed(evt);
            }
        });

        ncp_button.setBackground(new java.awt.Color(102, 204, 255));
        ncp_button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ncp_button.setText("NCP");
        ncp_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aap_label, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(congress_label, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bjp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nota_label, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ncp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aap_button, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(nota_button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(congress_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bjp_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ncp_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Partyname_label)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(Partyname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aap_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aap_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(congress_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(congress_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bjp_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bjp_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsp_label)
                    .addComponent(bsp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_label)
                    .addComponent(sp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ncp_label)
                    .addComponent(ncp_button, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nota_label)
                    .addComponent(nota_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void aap_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aap_buttonActionPerformed
        try{
             String party_name="AAP";
             choice(party_name);
             System.out.println("Hello");
            }
        catch(Exception ex){
                System.out.println(ex);
            }
                                                  
        // TODO add your handling code here:
    }//GEN-LAST:event_aap_buttonActionPerformed

    private void nota_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota_button1ActionPerformed
       try{
             String party_name="NOTA";
             choice(party_name);
            }
        catch(Exception ex){
                System.out.println(ex);
            }
       
    }//GEN-LAST:event_nota_button1ActionPerformed

    private void congress_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congress_button1ActionPerformed
       try{
             String party_name="CONGRESS";
             choice(party_name);
            }
        catch(Exception ex){
                System.out.println(ex);
            }
    }//GEN-LAST:event_congress_button1ActionPerformed

    private void bjp_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjp_button1ActionPerformed
        try{
             String party_name="BJP";
             choice(party_name);
            }
        catch(Exception ex){
                System.out.println(ex);
            }
    }//GEN-LAST:event_bjp_button1ActionPerformed

    private void bsp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsp_buttonActionPerformed
        try{
             String party_name="BSP";
             choice(party_name);
            }
        catch(Exception ex){
                System.out.println(ex);
            }
    }//GEN-LAST:event_bsp_buttonActionPerformed

    private void cp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_buttonActionPerformed
        try{
             String party_name="CP";
             choice(party_name);
            }
        catch(Exception ex){
                System.out.println(ex);
            }
    }//GEN-LAST:event_cp_buttonActionPerformed

    private void sp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp_buttonActionPerformed
        try{
             String party_name="SP";
             choice(party_name);
            }
        catch(Exception ex){
                System.out.println(ex);
            }
    }//GEN-LAST:event_sp_buttonActionPerformed
 

public static void main(String args[]) 
{
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 


        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Voting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

        catch (InstantiationException ex) 
        {
            java.util.logging.Logger.getLogger(Voting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Voting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Voting_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run() 
            {
                new Voting_page().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Partyname_label;
    private javax.swing.JButton aap_button;
    private javax.swing.JLabel aap_label;
    private javax.swing.JButton bjp_button1;
    private javax.swing.JLabel bjp_label;
    private javax.swing.JButton bsp_button;
    private javax.swing.JLabel bsp_label;
    private javax.swing.JButton congress_button1;
    private javax.swing.JLabel congress_label;
    private javax.swing.JButton cp_button;
    private javax.swing.JLabel cp_label;
    private javax.swing.JButton ncp_button;
    private javax.swing.JLabel ncp_label;
    private javax.swing.JButton nota_button1;
    private javax.swing.JLabel nota_label;
    private javax.swing.JButton sp_button;
    private javax.swing.JLabel sp_label;
    // End of variables declaration//GEN-END:variables
}
